# Exercise 1.A Numpy: Manipulating Arrays

In [3]:
import numpy as np

## Looping through arrays

In [ ]:
#Create a variable named arrA as a two-dimensional array
#containing (11, 12, 13) and (14, 15, 16) then print arrA.
arrA = np.array([(11, 12, 13), (14, 15, 16)])
print(arrA)
# used the comma to separte the group of list numbers

[[11 12 13]
 [14 15 16]]


In [8]:
#Loop through the first dimension of arrA (i.e. for x in arrA) and
#print each element multiplied by 2.

for x in arrA:
    print(x * 2)
# x is the number in the group list * 2

[22 24 26]
[28 30 32]


In [18]:
# loop through the second dimension of arrA (i.e. for y in x) and
#print each element multiplied by 2.
for x in arrA:
    for y in x:
        print(y * 2)



22
24
26
28
30
32


In [ ]:
# the first loop it loops through by each row [], []
# and in the second loop for y, its going throuhg each number individualy as a row
#basically printed in a vertical line vs horizontal group

In [ ]:
#Again loop through the second dimension of arrA (i.e. for y
#in x), but this time, assign x*2 to a variable named loop_result. Add another line
#of code to print loop_result, then add a comment to the cell to explain how/why
#this result is different.
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# output was repeated three times per group of numbers

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


In [25]:
print(loop_result)
# it only gave an output of the second set of numbers [14,15,16]
#its outside of the loop 


[28 30 32]


## Joining adnd stacking arrays

In [ ]:
#Create variable joined_array_1 and assign it the value of arrA concatenated
#with arrA on axis=0 (the default axis). Print joined_array_1.
arrA = np.array([(11, 12, 13), (14, 15, 16)])
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

#used arrA twice to combin it with joined


[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [34]:
#Create variable joined_array_2 and assign it the value of arrA concatenated
#with arrA on axis=1. Print joined_array_2.
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)




[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [35]:
#Create variable stacked_array_1 and assign it the value of joined_array_1
#stacked with joined_array_1 on the default axis. Print stacked_array_1.
stacked_array_1 = np.stack((joined_array_1, joined_array_1), axis=0)
print(stacked_array_1)



[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [ ]:
#Create variable stacked_array_2 and assign it the value of joined_array_1
#stacked with joined_array_2 on the default axis. What error message do you
#get? Add a comment to the cell to explain the error that comes back.

stacked_array_2 = np.stack((joined_array_1, joined_array_2), axis=0)
print(stacked_array_2)

#valueerror: all input arrays must have the same shape
# they dont have the same shape 2 is horizontal and 1 is vertical row


ValueError: all input arrays must have the same shape

In [38]:
#Create variable another_joined_array and assign it the value of
#joined_array_1 concatenated with arrA. Print another_joined_array.
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)



[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [ ]:
#Create variable another_2 and again assign it the value of joined_array_1
#concatenated with arrA, but this time on axis=1. What happens when you try to run
#this? Add a comment to the cell to paraphrase the error message in your own
#words.
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

#valueerror
# the two concatenate dont have the same number of rows
#one array has 4 size and the other has 2size



ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [ ]:
#Create a cell with three new variables (named as you choose). In each variable, use
#either the hstack(), vstack(), or dstack() function to stack arrA with arrA.
#Add a comment after each that explains what the function is doing. Print the results
#of each variable.

ex_1 = np.hstack((arrA, arrA))
print(ex_1)
print() # hstack arrays horizontlly adds columns

ex_2 = np.vstack((arrA, arrA))
print(ex_2)
print() # vstack stacks arrasy vertically adds rows

ex_3 = np.dstack((arrA, arrA))
print(ex_3)
# dstack stacks arrays adds depth/ height


[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [ ]:
#Create variable splitsky and assign it the value of joined_array_1 split into 2.
#Print the variable. Then add a comment to the cell to describe the result: how many
#arrays? Of how many dimensions each?
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

#the output was 2 arrays split evenly
#it split joined_array_1 into 2

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [ ]:
#Create variable spliterino and assign it the value of joined_array_1 split
#into 3. Print the variable. Then add a comment to the cell to describe the result: how
#many arrays? Of how many dimensions each?
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

#split joined_array_1 into three 
#the first array has both group of numbers, array2 only has the first half of the group of numbers
#the third array had the second half of the group of numbers



[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and replacing array values

In [ ]:
#In a code cell, create variable result_1. For the value of this variable, use where()
#to find each even number within arrA (hint, you’ll need to write a condition using %
#and ==). If the condition is met, print the value from arrA; if not met, print 'odd'.
#Print result_1.
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
#(condtion, valueiftrue, valueiffalse)
#condition divde by 2 if whole number means even, %no remainder thats why == 0
# when not whole number it will say odd in the array
print(result_1)




[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and filtering arrays

In [ ]:
#Create variable arrB as a 2-D array including the values (7,6), (13,5), and (7,3).
#Create another variable, arrB_sorted, and assign it the sorted value of arrB.
#Print arrB_sorted.
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
#sort, sorted each row individually
#i originally had arrB_sorted = arrB, but that did nothing
# and i had the .sort in the print statement print(np.sort(arrB))
print(arrB_sorted)




[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [ ]:
#Finally, let’s filter arrB using conditional logic. Start the cell with a print statement
#to again print the contents of arrB. Then create variable z with the value arrB < 7
#to look for values less than 7. Next create variable arrC, and assign it arrB[z].
#Print arrC.
print(arrB)
z = arrB < 7
# creates a boolean showing numbers less then 7
arrC = arrB[z]
print(arrC)
#the last set are the return values less then 7 [6 5 3]




[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [ ]:
#Applying the same sort of structure, how would you create a new conditional logic
#filter y to look for values greater than or equal to 7? Follow similar steps as above to
#create a new variable arrD to hold the filtered results, and print arrD.
print(arrB)
y = arrB >= 7
arrD = arrB[y]
print(arrD)

#same function as above just changed z for y and >= 7
# the last value show numbers 7 or higher [7 13 7]




[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
