# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random numbers

In [ ]:
#Create a variable named r_1 that contains a random set of integers between 1 and
#20 with a size of 2 elements. Print r_1.
r_1 = np.random.randint(1, 20, size=(2))
#.random.randint genertates a random integer
print(r_1)


[16  8]


In [ ]:
#Create a variable named r_2 that contains a random set of integers between 1 and
#20 with a size of 1 row, 2 columns. Print r_2.
r_2 = np.random.randint(1, 20, size=(1,2)) 
#size= 1row, 2columns
print(r_2)



[[ 2 14]]


In [6]:
#Create a variable named r_3 that contains a random set of floats between 0 and 1
#with a size of 2 rows, 1 columns. Print r_3.
r_3 = np.random.rand(2, 1)
#.random.rand generatess a random float between 0and 1
#no need for range just add size 
print(r_3)


[[0.87165124]
 [0.75830971]]


In [ ]:
#Create a variable named r_4 that contains a random set of integers between 20
#and 100 with a size of 4 rows, 5 columns. Print r_4.
r_4 = np.random.randint(20, 100, size=(4,5))
print(r_4)


[[37 59 66 76 36]
 [79 65 83 26 52]
 [49 21 39 52 37]
 [28 30 95 75 48]]


In [ ]:
#Create a variable named r_5 that contains a random set of floats between 0 and 1
#with a size of 4 rows, 5 columns. Print r_5.
r_5 = np.random.rand(4, 5)
print(r_5)


[[0.83187048 0.65456901 0.35784597 0.86882752 0.2669979 ]
 [0.57910186 0.53105029 0.39076422 0.76950236 0.95557535]
 [0.64913074 0.4881998  0.2365824  0.49752891 0.16037137]
 [0.20168498 0.66551291 0.81041781 0.81796515 0.57862901]]


## Generating Random Choice from an array

In [12]:
#Create a variable named students and assign it a 1-D array containing the names
#of 12 of your classmates.
students = ('Mike', 'Molly', 'Edward', 'Jacob', 'Bella', 'Blair','Nate', 'Dan', 'Charles', 'Serena', 'Harvey', 'Donna')
print(students)


('Mike', 'Molly', 'Edward', 'Jacob', 'Bella', 'Blair', 'Nate', 'Dan', 'Charles', 'Serena', 'Harvey', 'Donna')


In [ ]:
#Create a variable named call_on and use it to choose one random selection from
#students. Print call_on.
call_on = np.random.choice(students)
print(call_on)

Serena


In [ ]:
#Create a variable named breakout_groups and use it to choose a random
#sampling from students that is 3 rows, 4 columns in size. Print
#breakout_groups and examine the results – would this be an effective way to
#assign breakout groups? Why or why not? Add a comment to the cell with your
#response.
breakout_groups = np.random.choice(students, size=(5))
print(breakout_groups)

# this would not work but you have one person in two of the same groups
# need to remove duplicates in order to be effective

[['Bella' 'Mike' 'Nate' 'Serena']
 ['Serena' 'Molly' 'Serena' 'Harvey']
 ['Blair' 'Donna' 'Bella' 'Blair']]


In [ ]:
#Create a variable named call_on_weighted and use it to choose make five
#random selections from students, but this time assign different probability values
#that will determine how likely each student is to be selected. At least one student
#should have a zero likelihood of being called on, and at least one student should
#have a 30% likelihood of being called on. Distribute other probability values as you
#choose, and in a comment, explain the p values you assigned to each student. Print
#call_on_weighted.

call_on_weighted = np.random.choice(students, size=(5),
    p=[.30, .10, .00, .05, .05, .10,.05, .05, .05, .10, .10, .05])
# use random distribution to follow a certain probability density function
#p=[], probability value between 0 never occur and 1 always,total=must be 1
#all probability float number must add to 1.
# i gave mike .30 and edward .00 chnace of getting picked

print(call_on_weighted)


['Molly' 'Blair' 'Nate' 'Nate' 'Mike']


## Generating a Normal Distribution

In [ ]:
#Create a variable named bell_curve and assign it a random distribution for
#which the mean (peak of the curve) is 10, the standard deviation is 5, and the size of
#the returned array is 4 rows by 5 columns. Print bell_curve.
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)
#loc is the mean /peak of bell
#scale the spread/width standard deviation
#size the return array


[[ 8.86981481  8.46240126 17.84075034  8.70757551 17.2134096 ]
 [13.63637466 11.60603894 14.12718639  7.12942372 10.74087693]
 [15.8949376   6.76487543 16.78301309 19.01437987  8.48353602]
 [ 8.39189982 11.42716206  9.94345241  9.36144322  7.88593884]]
