# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample arrays

In [8]:
r_1 = np.random.randint(1, 20, size=(2))
r_2 = np.random.randint(1, 20, size=(1,2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4,5))
r_5 = np.random.rand(4, 5)


## Permutations

In [9]:
#First, print the current value of r_4
print(r_4)

[[93 64 39 47 73]
 [88 99 22 77 73]
 [31 28 89 77 51]
 [25 81 91 57 87]]


In [10]:
#Use np.random.shuffle to shuffle the values in r_4. Then print r_4 again to view
#the results.
np.random.shuffle(r_4)
print(r_4)

[[25 81 91 57 87]
 [93 64 39 47 73]
 [31 28 89 77 51]
 [88 99 22 77 73]]


### Looking at the results of the previous code block, how were the elements of the array shuffled? 

The last set was moved to the top and the second set was moved to the bottom
the third set stayed the same spot.
The order changed

In [13]:
#Create a new variable named new_shuffle, and assign it the value of a random
#permutation of r_4. Print new_shuffle, and then print r_4 again to compare
#values.
r_4 = np.random.randint(20, 100, size=(4,5))
print(r_4)
print()
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)




[[37 94 26 25 79]
 [21 20 54 49 77]
 [51 35 25 33 81]
 [52 90 83 90 42]]

[[51 35 25 33 81]
 [52 90 83 90 42]
 [21 20 54 49 77]
 [37 94 26 25 79]]


### when would you use shuffle versus permutation?
shuffle makes changes to the orignal array and left with only shuffled array. And pertutauion leaves the originall array intact and then returned a rearranged array so you have two a before and after.

## Mathematical operations

In [ ]:
#Print r_1 and r_2 as starting values, and also print the shape of each using the
#.shape attribute. Then print the result of r_1 plus r_2, using the add function. Also
#print the shape of the result.
r_1 = np.random.randint(1, 20, size=(2))
print(r_1)
print(r_1.shape)
print()

r_2 = np.random.randint(1, 20, size=(1,2))
print(r_2)
print(r_2.shape)
print()

result = np.add(r_1, r_2)
print(result)
print(result.shape)





[11  2]
(2,)

[[14  2]]
(1, 2)

[[25  4]]
(1, 2)


In [21]:
#Print r_1 and r_3 as starting values, and also print the shape of each using the
#.shape attribute. Then print the result of r_1 plus r_3, using the add function. Also
#print the shape of the result.
r_1 = np.random.randint(1, 20, size=(2))
print(r_1)
print(r_1.shape)
print()

r_3 = np.random.rand(2, 1)
print(r_3)
print(r_3.shape)
print()

result = np.add(r_1, r_3)
print(result)
print(result.shape)

[14  9]
(2,)

[[0.75605   ]
 [0.37341783]]
(2, 1)

[[14.75605     9.75605   ]
 [14.37341783  9.37341783]]
(2, 2)


In [22]:
#Print r_2 and r_4 again as starting values, and also print the shape of each using
#the .shape attribute. Then print the result of r_2 plus r_4, using the add function.
#Also print the shape of the result.
r_2 = np.random.randint(1, 20, size=(1,2))
print(r_2)
print(r_2.shape)
print()

r_4 = np.random.randint(20, 100, size=(4,5))
print(r_4)
print(r_4.shape)
print()

result = np.add(r_2, r_4)
print(result)
print(result.shape)



[[ 3 17]]
(1, 2)

[[79 92 28 24 64]
 [59 71 96 27 40]
 [88 60 28 46 48]
 [45 58 36 98 57]]
(4, 5)



ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [ ]:
#Create an expression to illustrate what happens when you add r_1 and r_4. What
#is the error message? How about adding r_2 or r_3 to r_4? Add a comment to the
#cell with your findings

np.add(r_1, r_4)
# this does not work b/c r1 (2), and r4 has 4 rows with 5 columns not the same size/shape
np.add(r_2, r_4)
# does not work r2 (1,2) size/shape
np.add(r_3, r_4)
#does not work r3 (2,1) size/shape

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

In [ ]:
#Show what happens if you add np.array([1]) to r_4
np.add(np.array([1]), r_4)

#adds the 1 to every number in r_4

array([[80, 93, 29, 25, 65],
       [60, 72, 97, 28, 41],
       [89, 61, 29, 47, 49],
       [46, 59, 37, 99, 58]])

In [ ]:
#Show what happens if you add np.array([[1]]) to r_4.
np.add(np.array([[1]]), r_4)

#nothing changes from above code output

array([[80, 93, 29, 25, 65],
       [60, 72, 97, 28, 41],
       [89, 61, 29, 47, 49],
       [46, 59, 37, 99, 58]])

In [ ]:
#Show what happens if you add np.array([1,1,1,1,1]) to r_4.
np.add(np.array([1, 1, 1, 1, 1]), r_4)
# 5one's and the r4 has 5 columns no change

array([[80, 93, 29, 25, 65],
       [60, 72, 97, 28, 41],
       [89, 61, 29, 47, 49],
       [46, 59, 37, 99, 58]])

In [ ]:
#What happens if you add np.array([[1],[1]]) to r_4? Add a comment to the
#cell with the error message this produces.
np.add(np.array([[1], [1]]), r_4)
# does not work differnt size shapes [1],[1] means 2 rows and 1 coloumn
#valueerror

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

In order for broadcasting to work, numpy compares the size/shape of the arrays to see if they are equal. If one array smaller the add() numpy will match and will add so it matches the bigger array

## Rounding

In [36]:
#Print r_3 to display the values you’ll be working with for the next few cells.
r_3 = np.random.rand(2, 1)
print(r_3)


[[0.31090822]
 [0.84606827]]


In [ ]:
#Round the values in r_3 using trunc
result = np.trunc(r_3)
print(result)
#returns number with decimal place chopped off

[[0.]
 [0.]]


In [ ]:
#Round the values in r_3 using fix
result = np.fix(r_3)
print(result)
#rounds to integer close to zero

[[0.]
 [0.]]


In [39]:
#Round the values in r_3 using floor
result = np.floor(r_3)
print(result)


[[0.]
 [0.]]


In [ ]:
#Round the values in r_3 using ceil.
result = np.ceil(r_3)
print(result)
#rounds up to integer

[[1.]
 [1.]]


In [49]:
#Round the values in r_3 using round, to 2 decimal places.
result = np.round(r_3, 2) #2 means 2 decimal places
print(result)
# if no (r_3,2) it will round to whole numbers[0.][1.]

[[0.31]
 [0.85]]


## Cumulative operations

In [50]:
#Print r_4 to display the values you’ll be working with for the next few cells.
r_4 = np.random.randint(20, 100, size=(4,5))
print(r_4)


[[42 35 36 71 31]
 [51 24 60 20 27]
 [33 35 54 83 71]
 [54 91 26 65 41]]


In [ ]:
#Print the sum of all values in r_4
result = np.sum(r_4) #total of all elements
print(result)

950


In [ ]:
#Print the sum of elements along the 0 axis for r_4.
result = np.sum(r_4, axis=0)
print(result) # adds down the coulmns each separatly output 5, 5 coloumns

[180 185 176 239 170]


In [ ]:
#Print the sum of elements along the 1 axis for r_4
result = np.sum(r_4, axis=1)
print(result) # out put 4, 4 rows


[215 182 276 277]


In [ ]:
#Print the cumulative sum (rolling total) of values in r_4.
result = np.cumsum(r_4)
print(result)
#

[ 42  77 113 184 215 266 290 350 370 397 430 465 519 602 673 727 818 844
 909 950]


In [58]:
#Print the cumulative sum (rolling total) of values along the 0 axis for r_4
result = np.cumsum(r_4, axis=0)
print(result)

[[ 42  35  36  71  31]
 [ 93  59  96  91  58]
 [126  94 150 174 129]
 [180 185 176 239 170]]


## Grocery problem

Create two new variables, bag1 and bag2. The first variable represents the
contents of a grocery bag, which contains two vegetables, three fruits, four boxes of
snacks, and no beverages. The second variable represents another grocery bag,
which contains no fruits, four vegetables, two beverages, and one box of snacks.
Assign an appropriate array to each variable that represents how many of each
category of item are in each bag. Print bag1 and bag2

In [59]:
bag1 = [2, 3, 4, 0]
# veggies, fruit, snack, bev
bag2 = [4, 0, 1, 2]
print(bag1)
print(bag2)

[2, 3, 4, 0]
[4, 0, 1, 2]


In [ ]:
#Write an expression to calculate the total number of items in each bag, and print the
#result in the form of a sentence: The first bag contains __ items, and the second bag
#contains ___ items.
total_items = np.sum(bag1)
total_items2 = np.sum(bag2)
print(f'The first bag contains {total_items} items, and the second bag contains {total_items2} items')




The first bag contains 9 items and the second bag contains 7 items


In [75]:
#Write an expression to calculate the total number of items in each category, and
#print the result in the form of a sentence: There are __ vegetables, __ fruits, __ boxes
#of snacks, and __ beverages in the two grocery bags.
veggie = bag1[0] + bag2[0]
fruits = bag1[1] + bag2[1]
snacks = bag1[2] + bag2[2]
bev = bag1[3] + bag2[3]

print(f'There are {veggie} vegetables, {fruits} fruits, {snacks} boxes of snacks, and {bev} beverages in the two grocery bags')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags


## Teamwork

The scenario for this set of problems is that you are volunteering with a voter registration campaign, and you have been asked to oversee a squad of door-knockers. There are three people on your team: Ali, Ben, and Carla. Your squad went out to knock on doors each evening last week, Monday through Friday, and now you are assembling that data.

In [84]:
#Ali reported knocking on 5 doors on Monday, 4 on Tuesday, 6 on Wednesday, 4 on
#Thursday, and 2 on Friday. Create a variable holding an array of these values.

ali = np.array([5, 4, 6, 4, 2])
print(ali)

[5 4 6 4 2]


In [85]:
#Ben missed Monday because he was out of town. He reported knocking on 5 on
#Tuesday, 5 on Wednesday, 3 on Thursday, and 4 on Friday. Create a variable holding
#an array of Ben’s values.
ben = np.array([0, 5, 5, 3, 4])
print(ben)

[0 5 5 3 4]


In [86]:
#Carla reported knocking on 3 doors on Monday, 6 on Tuesday, 3 on Thursday, and 4
#on Friday. She was sick on Wednesday so missed that day. Create a variable
#holding an array of Carla’s values.
carla = np.array([3, 6, 0, 3, 4])
print(carla)


[3 6 0 3 4]


In [87]:
#Compile the values reported by Ali, Ben, and Carla into a single array containing all
#door-knocks for the week, as all_knocks. Print the resulting array.
all_knocks = np.array([ali, ben, carla])
print(all_knocks)



[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [ ]:
#Use all_knocks to calculate the total number of doors that each person knocked
#on for the week, and also the total number of doors that the group collectively
#knocked on. Print the results.
np.sum(all_knocks, axis=1)
np.sum(all_knocks)
total_num = np.sum(all_knocks, axis=1) # axis 1 adds accross row vs axis 0 adds down the columns
group_total = np.sum(all_knocks)
print(total_num, 'each person on team')
print(f'Ali knocked {total_num[0]}') #[0],[1],[2] index value of each person
print(f'Ben knocked {total_num[1]}')
print(f'Carla knocked {total_num[2]}')
print(group_total, 'group total knocks')



[21 17 16] each person on team
Ali knocked 21
Ben knocked 17
Carla knocked 16
54 group total knocks


The organization you’re working with estimates that for every two door-knocks, one of those people will actually turn out to vote. For your report to the organization, what is the rolling total of estimated votes that your group was able to turn out, day by day for last week? (Hint: Start with the rolling total by day, then multiply that array by an appropriate value to get the result.)

In [ ]:
all_knocks = np.array([ali, ben, carla])

day_by_day = np.sum(all_knocks, axis=0) #adds the rows for each day total
rolling_total = np.cumsum(day_by_day)
turn_out = rolling_total *2 #turn over every 2knocks one will vote
print(turn_out)

[ 16  46  68  88 108]
