# Exercise 5.A NumPy fundamentals


In [3]:
import numpy as np

## Array Basics

In [16]:
#a) Create a standard Python list with the variable name fruits, containing the
#values apple, banana, cherry, and date
fruits = ['apple', 'banana', 'cherry', 'date']

In [ ]:
#b) Create a variable named arr_1 as a one-dimensional array containing fruits
#then print arr_1.
arr_1 = np.array(fruits) #using numpy array
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [ ]:
#c) Write an expression to check the data type of values contained in arr_1.
#After you run the cell, add a comment to explain what data type is returned. For
#the dtype, what does the letter mean, and what does the number mean?
#type(arr_1)
print(type(arr_1))
print(arr_1.dtype)
# u means unicode string text 
#6 means length of longest characters

<class 'numpy.ndarray'>
<U6


In [29]:
#d) Create a variable named arr_2 as a two-dimensional array containing
#(10, 11, 12) and (13, 14, 15) then print arr_2.
arr_2 = np.array([(10, 11, 12), (13, 14, 15)])
print(arr_2)
# had issues at first with the placement of brackets and parenthesis
# also had to add a comma in between the teo groups of numbers


[[10 11 12]
 [13 14 15]]


In [ ]:
#e) Use the transpose attribute to print arr_2 with its dimensions transposed
#(arr_2.T). In another cell, check: does this actually alter the value stored in
#arr_2? Include your answer in a comment.

transposed = arr_2.T # the has to be capital or you get error
print('Original array :\n', arr_2) #\n creates a line break for the group of numbers




Original array :
 [[10 11 12]
 [13 14 15]]


In [ ]:
#transposed 
print('Transposed array: \n', transposed)
#the transposed just lined them up like a row and then a new row with the other set of numbers
# no change to arr_2

Transposed array: 
 [[10 13]
 [11 14]
 [12 15]]


In [ ]:
#f) Create a variable named arr_3 as a two-dimensional array containing
#(1, 3, 5) and (2, 4, 6) then print arr_3.
arr_3 = np.array([(1, 3, 5), (2, 4, 6)])
print(arr_3)
# same layout as d


[[1 3 5]
 [2 4 6]]


In [36]:
#g) Create a variable named arr_4 as a one-dimensional array containing two
#values:
#using slicing notation, the element of arr_3 at index position 0, 2 and the element
#of arr_3 at index position 1, 1. Then print arr_4
arr_4 = np.array([arr_3[0,2], arr_3[1,1]])
print(arr_4)





[5 4]


In [ ]:
#h) Create a variable named arr_5 as a three-dimensional array containing all 1’s,
#with two values in each dimension. Then print arr_5.
arr_5 = np.ones((2, 2, 2))
print(arr_5)
#the 2 created groups of 2 for the 1
#the numpy.ones returns a array filled with 1's

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
